name: Absolute Citizen
favicon: null
layout_spectrum: 0.46256
typography_spectrum: 0.53385
title: Investor Residence and Citizenship Programs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3972c3'
    - '#b9c7ea'
    - '#6b513a'
    - '#060203'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.3869288407731801
purpose: []
