name: Absolute Citizen
favicon: null
layout_spectrum: 0.36972
typography_spectrum: 0.53385
title: Investor Residence and Citizenship Programs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfc9c9'
    - '#f5f5ed'
    - '#010101'
    - '#462025'
    - '#857f81'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
